var app = angular.module('dropDown', []);
app.controller('countriesCtrl', function()
{
    this.countries = [
        {id: 0, name:'Afghanistan'},
        {id: 1, name:'Albania'},
        {id: 2, name:'Algeria'},
        {id: 3, name:'Andorra'},
        {id: 4, name:'Angola'},
        {id: 5, name:'Antigua & Deps'},
        {id: 6, name:'Argentina'},
        {id: 7, name:'Armenia'},
        {id: 8, name:'Australia'},
        {id: 9, name:'Austria'},
        {id: 10, name:'Azerbaijan'},
        {id: 11, name:'Bahamas'},
        {id: 12, name:'Bahrain'},
        {id: 13, name:'Bangladesh'},
        {id: 14, name:'Barbados'},
        {id: 15, name:'Belarus'},
        {id: 16, name:'Belgium'},
        {id: 17, name:'Belize'},
        {id: 18, name:'Benin'},
        {id: 19, name:'Bhutan'},
        {id: 20, name:'Bolivia'},
        {id: 21, name:'Bosnia Herzegovina'},
        {id: 22, name:'Botswana'},
        {id: 23, name:'Brazil'},
        {id: 24, name:'Brunei'},
        {id: 25, name:'Bulgaria'},
        {id: 26, name:'Burkina'},
        {id: 27, name:'Burundi'},
        {id: 28, name:'Cambodia'},
        {id: 29, name:'Cameroon'},
        {id: 30, name:'Canada'},
        {id: 31, name:'Cape Verde'},
        {id: 32, name:'Central African Rep'},
        {id: 33, name:'Chad'},
        {id: 34, name:'Chile'},
        {id: 35, name:'China'},
        {id: 36, name:'Colombia'},
        {id: 37, name:'Comoros'},
        {id: 38, name:'Congo'},
        {id: 39, name:'Congo {Democratic Rep}'},
        {id: 40, name:'Costa Rica'},
        {id: 41, name:'Croatia'},
        {id: 42, name:'Cuba'},
        {id: 43, name:'Cyprus'},
        {id: 44, name:'Czech Republic'},
        {id: 45, name:'Denmark'},
        {id: 46, name:'Djibouti'},
        {id: 47, name:'Dominica'},
        {id: 48, name:'Dominican Republic'},
        {id: 49, name:'East Timor'},
        {id: 50, name:'Ecuador'},
        {id: 51, name:'Egypt'},
        {id: 52, name:'El Salvador'},
        {id: 53, name:'Equatorial Guinea'},
        {id: 54, name:'Eritrea'},
        {id: 55, name:'Estonia'},
        {id: 56, name:'Ethiopia'},
        {id: 57, name:'Fiji'},
        {id: 58, name:'Finland'},
        {id: 59, name:'France'},
        {id: 60, name:'Gabon'},
        {id: 61, name:'Gambia'},
        {id: 62, name:'Georgia'},
        {id: 63, name:'Germany'},
        {id: 64, name:'Ghana'},
        {id: 65, name:'Greece'},
        {id: 66, name:'Grenada'},
        {id: 67, name:'Guatemala'},
        {id: 68, name:'Guinea'},
        {id: 69, name:'Guinea-Bissau'},
        {id: 70, name:'Guyana'},
        {id: 71, name:'Haiti'},
        {id: 72, name:'Honduras'},
        {id: 73, name:'Hungary'},
        {id: 74, name:'Iceland'},
        {id: 75, name:'India'},
        {id: 76, name:'Indonesia'},
        {id: 77, name:'Iran'},
        {id: 78, name:'Iraq'},
        {id: 79, name:'Ireland {Republic}'},
        {id: 80, name:'Israel'},
        {id: 81, name:'Italy'},
        {id: 82, name:'Ivory Coast'},
        {id: 83, name:'Jamaica'},
        {id: 84, name:'Japan'},
        {id: 85, name:'Jordan'},
        {id: 86, name:'Kazakhstan'},
        {id: 87, name:'Kenya'},
        {id: 88, name:'Kiribati'},
        {id: 89, name:'Korea North'},
        {id: 90, name:'Korea South'},
        {id: 91, name:'Kosovo'},
        {id: 92, name:'Kuwait'},
        {id: 93, name:'Kyrgyzstan'},
        {id: 94, name:'Laos'},
        {id: 95, name:'Latvia'},
        {id: 96, name:'Lebanon'},
        {id: 97, name:'Lesotho'},
        {id: 98, name:'Liberia'},
        {id: 99, name:'Libya'},
        {id: 100, name:'Liechtenstein'},
        {id: 101, name:'Lithuania'},
        {id: 102, name:'Luxembourg'},
        {id: 103, name:'Macedonia'},
        {id: 104, name:'Madagascar'},
        {id: 105, name:'Malawi'},
        {id: 106, name:'Malaysia'},
        {id: 107, name:'Maldives'},
        {id: 108, name:'Mali'},
        {id: 109, name:'Malta'},
        {id: 110, name:'Marshall Islands'},
        {id: 111, name:'Mauritania'},
        {id: 112, name:'Mauritius'},
        {id: 113, name:'Mexico'},
        {id: 114, name:'Micronesia'},
        {id: 115, name:'Moldova'},
        {id: 116, name:'Monaco'},
        {id: 117, name:'Mongolia'},
        {id: 118, name:'Montenegro'},
        {id: 119, name:'Morocco'},
        {id: 120, name:'Mozambique'},
        {id: 121, name:'Myanmar, {Burma}'},
        {id: 122, name:'Namibia'},
        {id: 123, name:'Nauru'},
        {id: 124, name:'Nepal'},
        {id: 125, name:'Netherlands'},
        {id: 126, name:'New Zealand'},
        {id: 127, name:'Nicaragua'},
        {id: 128, name:'Niger'},
        {id: 129, name:'Nigeria'},
        {id: 130, name:'Norway'},
        {id: 131, name:'Oman'},
        {id: 132, name:'Pakistan'},
        {id: 133, name:'Palau'},
        {id: 134, name:'Panama'},
        {id: 135, name:'Papua New Guinea'},
        {id: 136, name:'Paraguay'},
        {id: 137, name:'Peru'},
        {id: 138, name:'Philippines'},
        {id: 139, name:'Poland'},
        {id: 140, name:'Portugal'},
        {id: 141, name:'Qatar'},
        {id: 142, name:'Romania'},
        {id: 143, name:'Russian Federation'},
        {id: 144, name:'Rwanda'},
        {id: 145, name:'St Kitts & Nevis'},
        {id: 146, name:'St Lucia'},
        {id: 147, name:'Saint Vincent & the Grenadines'},
        {id: 148, name:'Samoa'},
        {id: 149, name:'San Marino'},
        {id: 150, name:'Sao Tome & Principe'},
        {id: 151, name:'Saudi Arabia'},
        {id: 152, name:'Senegal'},
        {id: 153, name:'Serbia'},
        {id: 154, name:'Seychelles'},
        {id: 155, name:'Sierra Leone'},
        {id: 156, name:'Singapore'},
        {id: 157, name:'Slovakia'},
        {id: 158, name:'Slovenia'},
        {id: 159, name:'Solomon Islands'},
        {id: 160, name:'Somalia'},
        {id: 161, name:'South Africa'},
        {id: 162, name:'South Sudan'},
        {id: 163, name:'Spain'},
        {id: 164, name:'Sri Lanka'},
        {id: 165, name:'Sudan'},
        {id: 166, name:'Suriname'},
        {id: 167, name:'Swaziland'},
        {id: 168, name:'Sweden'},
        {id: 169, name:'Switzerland'},
        {id: 170, name:'Syria'},
        {id: 171, name:'Taiwan'},
        {id: 172, name:'Tajikistan'},
        {id: 173, name:'Tanzania'},
        {id: 174, name:'Thailand'},
        {id: 175, name:'Togo'},
        {id: 176, name:'Tonga'},
        {id: 177, name:'Trinidad & Tobago'},
        {id: 178, name:'Tunisia'},
        {id: 179, name:'Turkey'},
        {id: 180, name:'Turkmenistan'},
        {id: 181, name:'Tuvalu'},
        {id: 182, name:'Uganda'},
        {id: 183, name:'Ukraine'},
        {id: 184, name:'United Arab Emirates'},
        {id: 185, name:'United Kingdom'},
        {id: 186, name:'United States'},
        {id: 187, name:'Uruguay'},
        {id: 188, name:'Uzbekistan'},
        {id: 189, name:'Vanuatu'},
        {id: 190, name:'Vatican City'},
        {id: 191, name:'Venezuela'},
        {id: 192, name:'Vietnam'},
        {id: 193, name:'Yemen'},
        {id: 194, name:'Zambia'},
        {id: 195, name:'Zimbabwe'}
    ];
});

 